sudo: required
dist: trusty

language: haxe

os:
  - linux
#  - osx

haxe:
  - "3.4.7"
  - development

branches:
  only:
    - develop

env:
    matrix:
    - TARGET=js,node
    - TARGET=cpp
    - TARGET=cs,java
    - TARGET=neko,flash

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev ecx .
  - haxelib git hxmake https://github.com/eliasku/hxmake.git

script:
  - haxelib run hxmake test --override-test-target=${TARGET}