version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
  matrix:
    - TARGET: js,node
    - TARGET: hl,neko
    - TARGET: cpp
    - TARGET: cs,java
    - TARGET: flash

matrix:
  fast_finish: true

branches:
  only:
    - develop

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst neko --version 2.2.0 -y
  - cinst haxe --version 3.4.7 --ignore-dependencies -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib git hxmake https://github.com/eliasku/hxmake.git
  - haxelib dev ecx .

build: off

test_script:
  - haxelib run hxmake test --override-test-target="%TARGET%"
